apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: harbor.k8s.maimaiti.site/library/jenkins-demo:<BUILD_TAG>
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo
spec:
  selector:
    app: jenkins-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-demo
spec:
  rules:
  - host: jenkins-demo.k8s.maimaiti.site
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-demo
          servicePort: 8080
