server:
  port: 8761
spring:
  application:
    name: eureka
  profiles:
    active: ${ENVIRONMENT:dev}
eureka:
  environment: ${ENVIRONMENT:dev}
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
