apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka
data:
  eureka_server_address: http://eureka-0.eureka-service-internal.kube-system.svc.cluster.local:8761/eureka/,http://eureka-1.eureka-service-internal.kube-system.svc.cluster.local:8761/eureka/,http://eureka-2.eureka-service-internal.kube-system.svc.cluster.local:8761/eureka/

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service-internal
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka-service-internal"
  replicas: 3
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image:  harbor.k8s.maimaiti.site/library/eureka-server:v4
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: EUREKA_REPLICAS
          value: "3"
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka_server_address
        - name: ENVIRONMENT
          value: "prod"
        - name: JVM_OPTS
          value: "-Xms512m -Xmx512m"

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka
spec:
  rules:
  - host: eureka.k8s.maimaiti.site
    http:
      paths:
      - backend:
          serviceName: eureka
          servicePort: 8761
        path: /
