apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo-vue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-demo-vue
    spec:
      containers:
      - name: jenkins-demo-vue
        image: harbor.k8s.maimaiti.site/library/jenkins-demo-vue:<BUILD_TAG>
        env:
        - name: JVMSIZE
          value: -Xms512m -Xmx3g -Djava.security.egd=file:/dev/./urandom
        # - name: LOGPATH
        #   value: -Dlogging.path=/logs/mmd/mall-page/
        # - name: EUREKA
        #   value: -DEUREKA_SERVER_ADDRESS=http://eureka-service1.k8s.maimaiti.site/eureka/
        # - name: APOLLO
        #   value: -Dapollo.meta=http://devconf.maimaiti.site:8003
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-vue
spec:
  selector:
    app: jenkins-demo-vue
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-demo-vue
spec:
  rules:
  - host: jenkins-demo-vue.k8s.maimaiti.site
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-demo-vue
          servicePort: 8003
